# Generated by Django 4.2.4 on 2023-08-25 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='user uuid')),
                ('email', models.EmailField(max_length=250, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date of join')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login time')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swift_code_transaction', models.CharField(max_length=30)),
                ('seller_reputation', models.DecimalField(decimal_places=2, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerCardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_quality', models.CharField(max_length=16)),
                ('card_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('card_image', models.ImageField(upload_to='', verbose_name='OPTIONAL, card images do not need to be supplied, but sellers are encouraged to do so.')),
                ('card_url', models.URLField()),
                ('card_notes', models.TextField()),
                ('seller_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.selleraccount')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=250)),
                ('billing_address', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
