# Generated by Django 4.2.4 on 2023-08-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercarddetail',
            name='card_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellercarddetail',
            name='card_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellercarddetail',
            name='card_stock',
            field=models.IntegerField(default=1),
        ),
    ]
