# Generated by Django 4.2.4 on 2023-08-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercarddetail',
            name='card_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellercarddetail',
            name='card_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='OPTIONAL, card images do not need to be supplied, but sellers are encouraged to do so.'),
        ),
        migrations.AlterField(
            model_name='sellercarddetail',
            name='card_notes',
            field=models.TextField(blank=True),
        ),
    ]
