# Generated by Django 4.2.4 on 2023-08-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_sellercarddetail_card_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercarddetail',
            name='card_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
