# Generated by Django 4.2.4 on 2023-08-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_sellercarddetail_card_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercarddetail',
            name='card_name',
            field=models.TextField(default='CARDNAME'),
        ),
    ]
