# Generated by Django 4.2.4 on 2023-08-29 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_sellercarddetail_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercarddetail',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
